version: '2'
services:

  flight-app:
    build: /Users/samuel/IdeaProjects/flight-app
    ports:
      - "8080:8080"
    depends_on:
      - "db-flight-app"

  db-flight-app:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: flight-app-db
    volumes:
      - /var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  flight-app-db:
    external: true